### ISSUE TITLE
Remoting into WildFly (master)

### ISSUE THREAD

**Issue by kabir** [kabir/snapshot-ci#4]
```
name: XNIO and Remoting
components:
  - name: jboss-remoting
    org: jboss-remoting
    branch: '5.0'
    mavenOpts: -DskipTests
  - name: wildfly-core
    org: wildfly
    branch: master
    dependencies:
      - name: jboss-remoting
        property: version.org.jboss.remoting
  - name: wildfly
    org: wildfly
    branch: master
    dependencies:
      - name: wildfly-core
        property: version.org.wildfly.core
```
